[package]
name = "ronbun"
version = "0.1.0"
edition = "2018"
license = "MIT"

[dependencies]
actix-web = "3"
diesel = { version = "1.4.4", features = ["mysql", "chrono"] }
dotenv = "0.15.0"
chrono = "0.4"
