version: '3'
services:
  # Rust Application
  web:
    build: ./web
    image: web
    container_name: web
    tty: true
    user: root
    ports: 
      - 8989:8989
    environment: 
      - TZ=Asia/Tokyo
    volumes: 
      - ./src:/web/src
      - ./migrations:/web/migrations
      - ./dotenv:/web/.env
      - ./Cargo.toml:/web/Cargo.toml
      - cargo_target:/web/target
      - ./wait-for-it.sh:/tmp/wait-for-it.sh
    working_dir: /web
    depends_on:
      - db
    command: >
      /tmp/wait-for-it.sh -t 60 db:3306
      -- bash -c 'diesel setup && diesel migration run'

  # MySQL
  db:
    image: mysql:5.7
    container_name: db
    ports: 
      - 3306:3306
    restart: always
    environment: 
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ronbun_db
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
    volumes: 
      - ./db/my.cnf:/etc/mysql/conf.d/my_config.cnf
      # - ./db/mysql_init:/docker-entrypoint-initdb.d

  # phpMyAdmin
  pma:
    image: phpmyadmin/phpmyadmin:5
    container_name: pma
    ports: 
      - 8080:80
    restart: always
    environment: 
      - TZ=Asia/Tokyo
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    volumes:
      - /sessions
    depends_on: 
      - db

volumes:
  # Rust Crates
  cargo_target:
    driver: local
    external: false
